version: '3.8'

services:
  frontend:
    build:
      context: ./pet-booking-fe
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./pet-booking-fe:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pet-booking
    command: npm run dev

  backend:
    build:
      context: ./pet-booking-be
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pet_booking
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./pet-booking-be:/var/www/html
    depends_on:
      - db
    networks:
      - pet-booking

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pet_booking
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pet-booking

volumes:
  db_data:

networks:
  pet-booking:
    driver: bridge