version: '3.8'

services:
  frontend:
    build:
      context: ./pet-booking-fe
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - pet-booking

  backend:
    build:
      context: ./pet-booking-be
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:RxUHma7ggg3KVBAy+eF1OhAgs41VO4GXF3kJV+Y+8jQ=
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pet_booking
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - pet-booking

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pet_booking
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pet-booking

volumes:
  db_data:

networks:
  pet-booking:
    driver: bridge